/* Aiding Elements User Interface
 *      App 
 * 
 * autogenerated project file 
 */
using AidingElementsUserInterface.Core.AEUI_Data;
using AidingElementsUserInterface.Core.Auxiliaries;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Media.Imaging;
using System.Windows.Media;
using System.IO;

namespace AidingElementsUserInterface
{
    /// <summary>
    /// Interaction logic for App.xaml
    /// </summary>
    public partial class App : Application
    {
        XML_Handler handler = new XML_Handler();

        public App()
        {
            AddResources();
        }

        private void AddResources()
        {
            MainWindowResources();
            ButtonDataResources();
            CanvasDataResources();
            CoreDataResources();
            LabelDataResources();
            TextBoxDataResources();
        }

        private void ButtonDataResources()
        {
            CoreData buttonData = handler.ButtonData_load();

            if (buttonData == null)
            {
                buttonData = new MainWindowData();
            }

            Application.Current.Resources["ButtonData_background"] = buttonData.background.GetBrush();
            Application.Current.Resources["ButtonData_borderbrush"] = buttonData.borderbrush.GetBrush();
            Application.Current.Resources["ButtonData_foreground"] = buttonData.foreground.GetBrush();
            Application.Current.Resources["ButtonData_highlight"] = buttonData.highlight.GetBrush();

            Application.Current.Resources["ButtonData_cornerRadius"] = buttonData.cornerRadius;
            Application.Current.Resources["ButtonData_thickness"] = buttonData.thickness;

            Application.Current.Resources["ButtonData_fontSize"] = (double)buttonData.fontSize;
            Application.Current.Resources["ButtonData_fontFamily"] = buttonData.fontFamily;

            Application.Current.Resources["ButtonData_width"] = buttonData.width;
            Application.Current.Resources["ButtonData_height"] = buttonData.height;

            if (File.Exists(buttonData.imageFilePath))
            {
                Application.Current.Resources["ButtonData_image"] = new ImageBrush(new BitmapImage(new Uri(buttonData.imageFilePath)));
                Application.Current.Resources["ButtonData_background"] = Application.Current.Resources["ButtonData_image"];                
            }
        }

        private void CanvasDataResources()
        {
            CanvasData canvasData = handler.CanvasData_load();

            if (canvasData == null)
            {
                canvasData = new CanvasData();
            }

            Application.Current.Resources["CanvasData_background"] = canvasData.background.GetBrush();
            Application.Current.Resources["CanvasData_borderbrush"] = canvasData.borderbrush.GetBrush();
            Application.Current.Resources["CanvasData_foreground"] = canvasData.foreground.GetBrush();
            Application.Current.Resources["CanvasData_highlight"] = canvasData.highlight.GetBrush();
                                           
            Application.Current.Resources["CanvasData_cornerRadius"] = canvasData.cornerRadius;
            Application.Current.Resources["CanvasData_thickness"] = canvasData.thickness;
                                           
            Application.Current.Resources["CanvasData_fontSize"] = (double)canvasData.fontSize;
            Application.Current.Resources["CanvasData_fontFamily"] = canvasData.fontFamily;
                                           
            Application.Current.Resources["CanvasData_width"] = canvasData.width;
            Application.Current.Resources["CanvasData_height"] = canvasData.height;                                           
                                           
            Application.Current.Resources["CanvasData_canvasName"] = canvasData.canvasName;
            Application.Current.Resources["CanvasData_element_spacing"] = canvasData.element_spacing;
                                           
            Application.Current.Resources["CanvasData_grouping_displacement"] = canvasData.grouping_displacement;
            Application.Current.Resources["CanvasData_dragLevel"] = canvasData.dragLevel;
                                           
            Application.Current.Resources["CanvasData_hoverLevel"] = canvasData.hoverLevel;
            Application.Current.Resources["CanvasData_z_level_MAX"] = canvasData.z_level_MAX;
            Application.Current.Resources["CanvasData_z_level_MIN"] = canvasData.z_level_MIN;


            if (File.Exists(canvasData.imageFilePath))
            {
                Application.Current.Resources["CanvasData_image"] = new ImageBrush(new BitmapImage(new Uri(canvasData.imageFilePath)));
                Application.Current.Resources["CanvasData_background"] = Application.Current.Resources["CanvasData_image"];
            }
        }

        private void CoreDataResources()
        {
            CoreData coreData = handler.CoreData_load();

            if (coreData == null)
            {
                coreData = new CoreData();
            }

            Application.Current.Resources["CoreData_background"] = coreData.background.GetBrush();
            Application.Current.Resources["CoreData_borderbrush"] = coreData.borderbrush.GetBrush();
            Application.Current.Resources["CoreData_foreground"] = coreData.foreground.GetBrush();
            Application.Current.Resources["CoreData_highlight"] = coreData.highlight.GetBrush();

            Application.Current.Resources["CoreData_cornerRadius"] = coreData.cornerRadius;
            Application.Current.Resources["CoreData_thickness"] = coreData.thickness;

            Application.Current.Resources["CoreData_fontSize"] = (double)coreData.fontSize;
            Application.Current.Resources["CoreData_fontFamily"] = coreData.fontFamily;

            Application.Current.Resources["CoreData_width"] = coreData.width;
            Application.Current.Resources["CoreData_height"] = coreData.height;

            if (File.Exists(coreData.imageFilePath))
            {
                Application.Current.Resources["CoreData_image"] = new ImageBrush(new BitmapImage(new Uri(coreData.imageFilePath)));
                Application.Current.Resources["CoreData_background"] = Application.Current.Resources["CoreData_image"];
            }
        }

        private void LabelDataResources()
        {
            CoreData labelData = handler.LabelData_load();

            if (labelData == null)
            {
                labelData = new MainWindowData();
            }

            Application.Current.Resources["LabelData_background"] = labelData.background.GetBrush();
            Application.Current.Resources["LabelData_borderbrush"] = labelData.borderbrush.GetBrush();
            Application.Current.Resources["LabelData_foreground"] = labelData.foreground.GetBrush();
            Application.Current.Resources["LabelData_highlight"] = labelData.highlight.GetBrush();
                                           
            Application.Current.Resources["LabelData_cornerRadius"] = labelData.cornerRadius;
            Application.Current.Resources["LabelData_thickness"] = labelData.thickness;
                                           
            Application.Current.Resources["LabelData_fontSize"] = (double)labelData.fontSize;
            Application.Current.Resources["LabelData_fontFamily"] = labelData.fontFamily;
                                           
            Application.Current.Resources["LabelData_width"] = labelData.width;
            Application.Current.Resources["LabelData_height"] = labelData.height;

            if (File.Exists(labelData.imageFilePath))
            {
                Application.Current.Resources["LabelData_image"] = new ImageBrush(new BitmapImage(new Uri(labelData.imageFilePath)));
                Application.Current.Resources["LabelData_background"] = Application.Current.Resources["LabelData_image"];
            }
        }  

        private void MainWindowResources()
        {
            MainWindowData mainWindowData = handler.MainWindowData_load();

            if (mainWindowData == null)
            {
                mainWindowData = new MainWindowData();
            }

            Application.Current.Resources["MainWindow_background"] = mainWindowData.background.GetBrush();
            Application.Current.Resources["MainWindow_borderbrush"] = mainWindowData.borderbrush.GetBrush();
            Application.Current.Resources["MainWindow_foreground"] = mainWindowData.foreground.GetBrush();
            Application.Current.Resources["MainWindow_highlight"] = mainWindowData.highlight.GetBrush();

            Application.Current.Resources["MainWindow_cornerRadius"] = mainWindowData.cornerRadius;
            Application.Current.Resources["MainWindow_thickness"] = mainWindowData.thickness;

            Application.Current.Resources["MainWindow_fontSize"] = (double)mainWindowData.fontSize;
            Application.Current.Resources["MainWindow_fontFamily"] = mainWindowData.fontFamily;

            Application.Current.Resources["MainWindow_width"] = mainWindowData.width;
            Application.Current.Resources["MainWindow_height"] = mainWindowData.height;

            Application.Current.Resources["MainWindow_initialPosition_X"] = mainWindowData.initialPosition.X;
            Application.Current.Resources["MainWindow_initialPosition_Y"] = mainWindowData.initialPosition.Y;

            Application.Current.Resources["MainWindow_language"] = mainWindowData.language;

            if (File.Exists(mainWindowData.imageFilePath))
            {
                Application.Current.Resources["MainWindow_image"] = new ImageBrush(new BitmapImage(new Uri(mainWindowData.imageFilePath)));
                Application.Current.Resources["MainWindow_background"] = Application.Current.Resources["MainWindow_image"];
            }
        }

        private void TextBoxDataResources()
        {
            CoreData textBoxData = handler.TextBoxData_load();

            if (textBoxData == null)
            {
                textBoxData = new MainWindowData();
            }

            Application.Current.Resources["TextBoxData_background"] = textBoxData.background.GetBrush();
            Application.Current.Resources["TextBoxData_borderbrush"] = textBoxData.borderbrush.GetBrush();
            Application.Current.Resources["TextBoxData_foreground"] = textBoxData.foreground.GetBrush();
            Application.Current.Resources["TextBoxData_highlight"] = textBoxData.highlight.GetBrush();
                                           
            Application.Current.Resources["TextBoxData_cornerRadius"] = textBoxData.cornerRadius;
            Application.Current.Resources["TextBoxData_thickness"] = textBoxData.thickness;
                                           
            Application.Current.Resources["TextBoxData_fontSize"] = (double)textBoxData.fontSize;
            Application.Current.Resources["TextBoxData_fontFamily"] = textBoxData.fontFamily;
                                           
            Application.Current.Resources["TextBoxData_width"] = textBoxData.width;
            Application.Current.Resources["TextBoxData_height"] = textBoxData.height;

            if (File.Exists(textBoxData.imageFilePath))
            {
                Application.Current.Resources["TextBoxData_image"] = new ImageBrush(new BitmapImage(new Uri(textBoxData.imageFilePath)));
                Application.Current.Resources["TextBoxData_background"] = Application.Current.Resources["TextBoxData_image"];
            }
        }
    }
}
