/* Aiding Elements User Interface
 *      App 
 * 
 * autogenerated project file 
 */
using AidingElementsUserInterface.Core.AEUI_Data;
using AidingElementsUserInterface.Core.Auxiliaries;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Media.Imaging;
using System.Windows.Media;
using System.IO;
using AidingElementsUserInterface.Core;
using AidingElementsUserInterface.Core.AEUI_UserControls;

namespace AidingElementsUserInterface
{
    /// <summary>
    /// Interaction logic for App.xaml
    /// </summary>
    public partial class App : Application
    {
        XML_Handler handler = new XML_Handler();

        public App()
        {
            AddResources();
        }

        private void AddResources()
        {
            ButtonDataResources();
            CoreDataResources();
            LabelDataResources();
            TextBoxDataResources();
        }

        private void ButtonDataResources()
        {
            CoreData buttonData = handler.ButtonData_load();

            if (buttonData == null)
            {
                buttonData = new CoreData();
            }

            Application.Current.Resources["ButtonData_background"] = buttonData.background.GetBrush();
            Application.Current.Resources["ButtonData_borderbrush"] = buttonData.borderbrush.GetBrush();
            Application.Current.Resources["ButtonData_foreground"] = buttonData.foreground.GetBrush();
            Application.Current.Resources["ButtonData_highlight"] = buttonData.highlight.GetBrush();

            Application.Current.Resources["ButtonData_cornerRadius"] = buttonData.cornerRadius;
            Application.Current.Resources["ButtonData_thickness"] = buttonData.thickness;

            Application.Current.Resources["ButtonData_fontSize"] = (double)buttonData.fontSize;
            Application.Current.Resources["ButtonData_fontFamily"] = buttonData.fontFamily;

            Application.Current.Resources["ButtonData_width"] = buttonData.width;
            Application.Current.Resources["ButtonData_height"] = buttonData.height;

            if (File.Exists(buttonData.background.brushpath))
            {
                Application.Current.Resources["ButtonData_image"] = buttonData.background.GetBrush();
                Application.Current.Resources["ButtonData_background"] = buttonData.background.GetBrush();
            }
        }

        private void CoreDataResources()
        {
            CoreData coreData = handler.CoreData_load();

            if (coreData == null)
            {
                coreData = new CoreData();
            }

            Application.Current.Resources["CoreData_background"] = coreData.background.GetBrush();
            Application.Current.Resources["CoreData_borderbrush"] = coreData.borderbrush.GetBrush();
            Application.Current.Resources["CoreData_foreground"] = coreData.foreground.GetBrush();
            Application.Current.Resources["CoreData_highlight"] = coreData.highlight.GetBrush();

            Application.Current.Resources["CoreData_cornerRadius"] = coreData.cornerRadius;
            Application.Current.Resources["CoreData_thickness"] = coreData.thickness;

            Application.Current.Resources["CoreData_fontSize"] = (double)coreData.fontSize;
            Application.Current.Resources["CoreData_fontFamily"] = coreData.fontFamily;

            Application.Current.Resources["CoreData_width"] = coreData.width;
            Application.Current.Resources["CoreData_height"] = coreData.height;

            if (File.Exists(coreData.background.brushtype))
            {
                Application.Current.Resources["CoreData_image"] = coreData.background.GetBrush();
                Application.Current.Resources["CoreData_background"] = coreData.background.GetBrush();
            }
        }

        private void LabelDataResources()
        {
            CoreData labelData = handler.LabelData_load();

            if (labelData == null)
            {
                labelData = new CoreData();
            }

            Application.Current.Resources["LabelData_background"] = labelData.background.GetBrush();
            Application.Current.Resources["LabelData_borderbrush"] = labelData.borderbrush.GetBrush();
            Application.Current.Resources["LabelData_foreground"] = labelData.foreground.GetBrush();
            Application.Current.Resources["LabelData_highlight"] = labelData.highlight.GetBrush();

            Application.Current.Resources["LabelData_cornerRadius"] = labelData.cornerRadius;
            Application.Current.Resources["LabelData_thickness"] = labelData.thickness;

            Application.Current.Resources["LabelData_fontSize"] = (double)labelData.fontSize;
            Application.Current.Resources["LabelData_fontFamily"] = labelData.fontFamily;

            Application.Current.Resources["LabelData_width"] = labelData.width;
            Application.Current.Resources["LabelData_height"] = labelData.height;

            if (File.Exists(labelData.background.brushpath))
            {
                Application.Current.Resources["LabelData_image"] = labelData.background.GetBrush();
                Application.Current.Resources["LabelData_background"] = labelData.background.GetBrush();
            }
        }

        private void TextBoxDataResources()
        {
            CoreData textBoxData = handler.TextBoxData_load();

            if (textBoxData == null)
            {
                textBoxData = new CoreData();
            }

            Application.Current.Resources["TextBoxData_background"] = textBoxData.background.GetBrush();
            Application.Current.Resources["TextBoxData_borderbrush"] = textBoxData.borderbrush.GetBrush();
            Application.Current.Resources["TextBoxData_foreground"] = textBoxData.foreground.GetBrush();
            Application.Current.Resources["TextBoxData_highlight"] = textBoxData.highlight.GetBrush();

            Application.Current.Resources["TextBoxData_cornerRadius"] = textBoxData.cornerRadius;
            Application.Current.Resources["TextBoxData_thickness"] = textBoxData.thickness;

            Application.Current.Resources["TextBoxData_fontSize"] = (double)textBoxData.fontSize;
            Application.Current.Resources["TextBoxData_fontFamily"] = textBoxData.fontFamily;

            Application.Current.Resources["TextBoxData_width"] = textBoxData.width;
            Application.Current.Resources["TextBoxData_height"] = textBoxData.height;

            if (File.Exists(textBoxData.background.brushpath))
            {
                Application.Current.Resources["TextBoxData_image"] = textBoxData.background.GetBrush();
                Application.Current.Resources["TextBoxData_background"] = textBoxData.background.GetBrush();
            }
        }

    }
}
